name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04  # 升级到 22.04 避免排队和过期问题

    strategy:
      matrix:
        node-version: [14.x] # 建议放弃 10/12，因为在 22.04 上很难安装

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Repositories
      run: |
        # Chrome
        sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        # Gazebo
        sudo wget https://packages.osrfoundation.org/gazebo.key -O /usr/share/keyrings/gazebo-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/gazebo-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list

    - name: Install Dependencies
      run: |
        sudo apt update
        # 注意：Ubuntu 22.04 使用 libgazebo-dev
        sudo apt install -y xvfb google-chrome-stable gnustep-base-runtime libjansson-dev libboost-dev imagemagick libtinyxml-dev git cmake build-essential wget libgazebo-dev

    - name: Setup Chrome for Headless Testing
      run: |
        sudo wget -q -O /usr/bin/xvfb-chrome https://gist.githubusercontent.com/chapulina/a80bd83d3494c96dc9eead843579c435/raw/7d304595d401c1265b533626d542ace7e6916002/xvfb-chrome
        sudo ln -sf /usr/bin/xvfb-chrome /usr/bin/google-chrome
        sudo chmod 755 /usr/bin/google-chrome

    - name: Build and Test
      run: |
        sudo npm install -g grunt
        npm run deploy --verbose
        npm run test:headless
        npm run update
        npm run docs
      env:
        CI: true